/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as ResumeExtractorRouteImport } from './routes/resume-extractor'
import { Route as SkillGapRouteImport } from './routes/skill-gap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeExtractorRoute = ResumeExtractorRouteImport.update({
  id: '/resume-extractor',
  path: '/resume-extractor',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillGapRoute = SkillGapRouteImport.update({
  id: '/skill-gap',
  path: '/skill-gap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/evidence': typeof EvidenceRoute
  '/resume-extractor': typeof ResumeExtractorRoute
  '/skill-gap': typeof SkillGapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/evidence': typeof EvidenceRoute
  '/resume-extractor': typeof ResumeExtractorRoute
  '/skill-gap': typeof SkillGapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assessments': typeof AssessmentsRoute
  '/evidence': typeof EvidenceRoute
  '/resume-extractor': typeof ResumeExtractorRoute
  '/skill-gap': typeof SkillGapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/assessments' | '/evidence' | '/resume-extractor' | '/skill-gap'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/assessments' | '/evidence' | '/resume-extractor' | '/skill-gap'
  id:
    | '__root__'
    | '/'
    | '/assessments'
    | '/evidence'
    | '/resume-extractor'
    | '/skill-gap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssessmentsRoute: typeof AssessmentsRoute
  EvidenceRoute: typeof EvidenceRoute
  ResumeExtractorRoute: typeof ResumeExtractorRoute
  SkillGapRoute: typeof SkillGapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume-extractor': {
      id: '/resume-extractor'
      path: '/resume-extractor'
      fullPath: '/resume-extractor'
      preLoaderRoute: typeof ResumeExtractorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skill-gap': {
      id: '/skill-gap'
      path: '/skill-gap'
      fullPath: '/skill-gap'
      preLoaderRoute: typeof SkillGapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssessmentsRoute: AssessmentsRoute,
  EvidenceRoute: EvidenceRoute,
  ResumeExtractorRoute: ResumeExtractorRoute,
  SkillGapRoute: SkillGapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
